
export class Certficate {

     private allCertficates =[
        { "name": "Aakash Garg", "email": "aakashgarg19@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/aakash-garg-7757401.jpg" },
        { "name": "Abhilash Kulkarni", "email": "ababhilash@deloitte.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/abhilash-kulkarni-8041241.jpg" },
        { "name": "Abhilash Rana", "email": "abhilashranout@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/abhilash-rana-7658084.jpg" },
        { "name": "Abhilash Srivastava", "email": "abhilash@smartjoules.in", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/abhilash-srivastava-7977681.jpg" },
        { "name": "Abhinav Kant", "email": "Abhinav.Kant@aristocrat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/abhinav-kant-7745525.jpg" },
        { "name": "Abhishek Kant", "email": "abhishek@abhishekkant.net", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/abhishek-kant-8027728.jpg" },
        { "name": "Abhishek Mahajan", "email": "abhi.mahajan.7712@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/abhishek-mahajan-7545674.jpg" },
        { "name": "Abhishek Srivastava", "email": "abhishek.srivastava@celebaltech.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/abhishek-srivastava-8040581.jpg" },
        { "name": "Adarshram S Tripathi", "email": "adarshramtripathi1996@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/adarshram-s-tripathi-7961679.jpg" },
        { "name": "Aditya Jha", "email": "4adityajha@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/aditya-jha-7987222.jpg" },
        { "name": "Ajay Kumar", "email": "ajaykumarjha85@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/ajay-kumar-7545727.jpg" },
        { "name": "Ajay Subhash Badhe", "email": "badheajay5391@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/ajay-subhash-badhe-7905186.jpg" },
        { "name": "Ajinkya Shinde", "email": "ajinkya.shinde@iauro.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/ajinkya-shinde-7979864.jpg" },
        { "name": "Akanksha Bhasin", "email": "akanksha.bhasin@symbl.ai", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/akanksha-bhasin-7773478.jpg" },
        { "name": "Akansha Jain", "email": "jakansha2001@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/akansha-jain-7999965.jpg" },
        { "name": "Akash Deep Gupta", "email": "AkashDeep.Gupta@aristocrat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/akash-deep-gupta-7745013.jpg" },
        { "name": "Akash Kriplani", "email": "aakash23kriplani@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/akash-kriplani-7758952.jpg" },
        { "name": "Akshat Jindal", "email": "akshatjindal215@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/akshat-jindal-7759996.jpg" },
        { "name": "Akshat Sharma", "email": "aksh.sharma512@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/akshat-sharma-7877563.jpg" },
        { "name": "Akshay Kumar Sharma", "email": "akshay.sharma@thecompetenza.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/akshay-kumar-sharma-7769553.jpg" },
        { "name": "Alicia Morris", "email": "aliciam@syncfusion.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/alicia-morris-8002228.jpg" },
        { "name": "Alin Ann Thomas", "email": "alinannthomas91@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/alin-ann-thomas-8019081.jpg" },
        { "name": "Alok Trivedi", "email": "Alok.Trivedi@aristocrat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/alok-trivedi-7745596.jpg" },
        { "name": "Aman Gupta", "email": "amangupta@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/aman-gupta-7783058.jpg" },
        { "name": "Amarsinh Baburao Farakte", "email": "faraktesir@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/amarsinh-baburao-farakte-7866097.jpg" },
        { "name": "Ambikesh Pratap Singh", "email": "AmbikeshPratap.Singh@aristocrat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/ambikesh-pratap-singh-7745719.jpg" },
        { "name": "Amit Kumar Dwivedi", "email": "amitdubey.108@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/amit-kumar-dwivedi-7777031.jpg" },
        { "name": "Amit Kumar Mishra", "email": "24.amit@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/amit-kumar-mishra-7785406.jpg" },
        { "name": "Amit Kumar Thakur", "email": "amkt18@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/amit-kumar-thakur-7774447.jpg" },
        { "name": "Amit Srivastava", "email": "asamit78@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/amit-srivastava-7550263.jpg" },
        { "name": "Amit Suyal", "email": "amitsuyal175@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/amit-suyal-7663909.jpg" },
        { "name": "Amit Tyagi", "email": "incredibleamittyagi@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/amit-tyagi-8039042.jpg" },
        { "name": "Anand Kumar M", "email": "Murugappan_Anand_Kumar@cat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/anand-kumar-m-7967867.jpg" },
        { "name": "Anas Khan", "email": "anas.khan@pentaknot.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/anas-khan-7773533.jpg" },
        { "name": "Anil Dutt Sharma", "email": "anilgenius2000@yahoo.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/anil-dutt-sharma-7625337.jpg" },
        { "name": "Anil Kumar Singh", "email": "anil.singh581@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/anil-kumar-singh-7935187.jpg" },
        { "name": "Animesh Udawat", "email": "animeshudawat@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/animesh-udawat-7973891.jpg" },
        { "name": "Anirudh Varma", "email": "anirudh@spotdraft.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/anirudh-varma-7955824.jpg" },
        { "name": "Anish Mathur", "email": "anishmatj@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/anish-mathur-7944489.jpg" },
        { "name": "Anish Verma", "email": "Anish.Verma@aristocrat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/anish-verma-7745082.jpg" },
        { "name": "Ankesh Dave", "email": "ankeshdave@outlook.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/ankesh-dave-7960787.jpg" },
        { "name": "Ankit Bansal", "email": "mvpankit@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/ankit-bansal-7544593.jpg" },
        { "name": "Ankit Jindal", "email": "nkit.jindal@taazaa.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/ankit-jindal-7775329.jpg" },
        { "name": "Ankit Kaushik", "email": "altruistakki@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/ankit-kaushik-7771884.jpg" },
        { "name": "Ankit Kumar Sharma", "email": "aks.computerexpert@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/ankit-kumar-sharma-7532497.jpg" },
        { "name": "Ankit Prajapati", "email": "aprajapati06@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/ankit-prajapati-7905454.jpg" },
        { "name": "Ankita Minanath Medhekar", "email": "ankitamedhekar8@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/ankita-minanath-medhekar-7699496.jpg" },
        { "name": "Ankita Saloni", "email": "saloniankita23@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/ankita-saloni-7864250.jpg" },
        { "name": "Ankur Mekvan", "email": "ankur@imriel.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/ankur-mekvan-7926384.jpg" },
        { "name": "Ankur Singhal", "email": "ankur.singhal@thalesgroup.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/ankur-singhal-7746194.jpg" },
        { "name": "Anshul Dubey", "email": "Anshul.Dubey@aristocrat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/anshul-dubey-7745761.jpg" },
        { "name": "Anup Kumar Sharma", "email": "appsharma@outlook.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/anup-kumar-sharma-7904130.jpg" },
        { "name": "Anuradha Sadh", "email": "anuradha.sadh@thecompetenza.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/anuradha-sadh-7887263.jpg" },
        { "name": "Anurag Sharma", "email": "anurag.sharma172@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/anurag-sharma-7671859.jpg" },
        { "name": "Anurag Singh", "email": "anurag@imriel.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/anurag-singh-7926386.jpg" },
        { "name": "Apoorv Dixit", "email": "Apoorv.Dixit@aristocrat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/apoorv-dixit-7744555.jpg" },
        { "name": "Apoorv Dwivedi", "email": "apoorvd14@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/apoorv-dwivedi-8039084.jpg" },
        { "name": "Arjun Ramavat", "email": "arjun.ramavat1@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/arjun-ramavat-7532405.jpg" },
        { "name": "Arpan Garg", "email": "arpansac@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/arpan-garg-7953440.jpg" },
        { "name": "Arpan Sthapit", "email": "questpond@questpond.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/arpan-sthapit-8035363.jpg" },
        { "name": "Arpit Gupta", "email": "gupta.arpit03@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/arpit-gupta-7877268.jpg" },
        { "name": "Arun Kumar Natesan", "email": "arunkumar01096@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/arun-kumar-natesan-7687311.jpg" },
        { "name": "Arushi Walia", "email": "arushi.walia@thalesgroup.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/arushi-walia-7746195.jpg" },
        { "name": "Ashansh Lokhande", "email": "lokhandeashansh@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/ashansh-lokhande-7776912.jpg" },
        { "name": "Ashish Bagdane", "email": "ashish.bagdane@neptune-ubi.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/ashish-bagdane-7815903.jpg" },
        { "name": "Ashish Gaikwad", "email": "questpond@questpond.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/ashish-gaikwad-8035363.jpg" },
        { "name": "Ashish Gupta", "email": "Ashish.Gupta@aristocrat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/ashish-gupta-7744991.jpg" },
        { "name": "Ashishkumar Vishwakarma", "email": "ashishvishwakarma93@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/ashishkumar-vishwakarma-7553711.jpg" },
        { "name": "Ashwarya Jethi", "email": "ashwaryajethi@yahoo.co.in", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/ashwarya-jethi-7716649.jpg" },
        { "name": "Ashwin Balaji", "email": "ashwinbala17@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/ashwin-balaji-7687915.jpg" },
        { "name": "Ashwini Kumar Jha", "email": "ashwini.jsr@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/ashwini-kumar-jha-8010574.jpg" },
        { "name": "Atif Khan", "email": "atif@smartjoules.in", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/atif-khan-7979484.jpg" },
        { "name": "Atul Gupta", "email": "inform2atul@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/atul-gupta-8035834.jpg" },
        { "name": "Atul Setu", "email": "atul.setu@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/atul-setu-7544772.jpg" },
        { "name": "Avadhesh Kumar", "email": "Avadhesh.Kumar@aristocrat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/avadhesh-kumar-7745681.jpg" },
        { "name": "Avani Patoria", "email": "apatoria@sharpquest.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/avani-patoria-7879654.jpg" },
        { "name": "Avantika.Karwasara", "email": "avantika.karwasara@thalesgroup.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/avantika.karwasara-7746196.jpg" },
        { "name": "Avinash Patra", "email": "avinash.patra8@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/avinash-patra-8032387.jpg" },
        { "name": "B Uday Kumar", "email": "udaykumar.net2@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/b-uday-kumar-7557462.jpg" },
        { "name": "Babandeep Singh", "email": "er.babandeep@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/babandeep-singh-7875595.jpg" },
        { "name": "Balaji Varadharajan", "email": "balaji.v@sisystems.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/balaji-varadharajan-7994098.jpg" },
        { "name": "Ben Dechrai", "email": "ben@dechrai.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/ben-dechrai-8010509.jpg" },
        { "name": "Bharath Ravi", "email": "bharath@spotdraft.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/bharath-ravi-7955827.jpg" },
        { "name": "Bhavana Prafulla Patil", "email": "bpatil2@slb.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/bhavana-prafulla-patil-7960788.jpg" },
        { "name": "Bhavya Khurana", "email": "bhavyakhurana002@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/bhavya-khurana-7707624.jpg" },
        { "name": "Binay Kumar", "email": "Finmart4u@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/binay-kumar-8033393.jpg" },
        { "name": "Bobby Devappa Chilami", "email": "bobbychilami@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/bobby-devappa-chilami-7866099.jpg" },
        { "name": "Chaitanya Chunduri", "email": "chaitanyach@outlook.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/chaitanya-chunduri-7775878.jpg" },
        { "name": "Chakit Arora", "email": "arorachakit@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/chakit-arora-7966247.jpg" },
        { "name": "Chandani Prajapati", "email": "chandaniprajapati96@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/chandani-prajapati-7905455.jpg" },
        { "name": "Chellappan Rajan", "email": "vrchellappan@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/chellappan-rajan-7533146.jpg" },
        { "name": "Chetan Ramakrishna", "email": "chetan.r@enverus.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/chetan-ramakrishna-7955892.jpg" },
        { "name": "Chinmay Bhave", "email": "csbhave07@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/chinmay-bhave-7618832.jpg" },
        { "name": "Chirag Thaker", "email": "chirag.g.thaker@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/chirag-thaker-7532404.jpg" },
        { "name": "Christopher Isaac Sunder K", "email": "christopherk@syncfusion.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/christopher-isaac-sunder-k-7909340.jpg" },
        { "name": "Cyril Thomas Varghese", "email": "cyrilthomas.varghese@nice.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/cyril-thomas-varghese-7970385.jpg" },
        { "name": "Debal Choudhary", "email": "questpond@questpond.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/debal-choudhary-8035363.jpg" },
        { "name": "Deep Govani", "email": "deepgovani9@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/deep-govani-7533115.jpg" },
        { "name": "Deepak Kumar", "email": "deepak.kumar4@blackrock.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/deepak-kumar-7971080.jpg" },
        { "name": "Deepansh Khurana", "email": "deepanshk00@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/deepansh-khurana-7782900.jpg" },
        { "name": "Deven Joshi", "email": "deven@getstream.io", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/deven-joshi-7988590.jpg" },
        { "name": "Dharam Vijay Dhoke", "email": "dharam.dhoke@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/dharam-vijay-dhoke-7905184.jpg" },
        { "name": "Dharmen Shah", "email": "shhdharmen@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/dharmen-shah-7694648.jpg" },
        { "name": "Dharmik Dalwadi", "email": "dharmik.dalwadi@seaflux.tech", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/dharmik-dalwadi-7627636.jpg" },
        { "name": "Dheeraj Kumar", "email": "kumardheerajs@yahoo.co.in", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/dheeraj-kumar-7625336.jpg" },
        { "name": "Dhruv Garg", "email": "dhruv.garg05@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/dhruv-garg-7544500.jpg" },
        { "name": "Diljit Singh", "email": "diljitsingh79860@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/diljit-singh-7792355.jpg" },
        { "name": "Dinesh Beniwal", "email": "dbeniwal21@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/dinesh-beniwal-8035824.jpg" },
        { "name": "Dinesh Bist", "email": "questpond@questpond.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/dinesh-bist-8035363.jpg" },
        { "name": "Dinesh Kumar", "email": "dinesh_here@outlook.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/dinesh-kumar-7687916.jpg" },
        { "name": "Dinesh Kumar P", "email": "dineshkp27@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/dinesh-kumar-p-7708608.jpg" },
        { "name": "Divyang Hingrajiya", "email": "divyanghingarajiya@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/divyang-hingrajiya-7780029.jpg" },
        { "name": "Dr. Sanjay Annasaheb Chavan", "email": "vishwarajchavan123@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/dr.-sanjay-annasaheb-chavan-7866093.jpg" },
        { "name": "Dushyant Purohit", "email": "dushyant.purohit87@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/dushyant-purohit-7955615.jpg" },
        { "name": "Gaganjot Kaur", "email": "gaganjot.kaur@vtnetzwelt.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/gaganjot-kaur-8034434.jpg" },
        { "name": "Gaurav Bajaj", "email": "gaurav.bajaj@vtnetzwelt.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/gaurav-bajaj-8034435.jpg" },
        { "name": "Gaurav Bansal", "email": "Gaurav.Bansal@aristocrat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/gaurav-bansal-7745003.jpg" },
        { "name": "Gaurav Kishor Chauhan", "email": "chgav007@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/gaurav-kishor-chauhan-7780160.jpg" },
        { "name": "Gaurav Madaan", "email": "gaurav@niwi.ai", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/gaurav-madaan-7533245.jpg" },
        { "name": "Gaurav Mukherjee", "email": "g.mukherjee@f5.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/gaurav-mukherjee-8019070.jpg" },
        { "name": "Gaurav Suhanda", "email": "gaurav.suhanda@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/gaurav-suhanda-7958643.jpg" },
        { "name": "Gaurav Upadhyay", "email": "gauravupadhyay28@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/gaurav-upadhyay-7543974.jpg" },
        { "name": "Gauri Chhabra", "email": "gchhabra@sagunaconsulting.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/gauri-chhabra-8008167.jpg" },
        { "name": "Gobika", "email": "gobika21@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/gobika-7533147.jpg" },
        { "name": "Gopal Sharma", "email": "gopal.sharma@qservicesit.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/gopal-sharma-7882597.jpg" },
        { "name": "Gourav Garg", "email": "grvgarg475@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/gourav-garg-7554359.jpg" },
        { "name": "Gowtham Kannan", "email": "gowtham.kannan@cat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/gowtham-kannan-7966989.jpg" },
        { "name": "Gulshan Kumar", "email": "gulku@7n.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/gulshan-kumar-7939153.jpg" },
        { "name": "Gurpreet Singh", "email": "webdeveloper@nextgenapps.in", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/gurpreet-singh-7746530.jpg" },
        { "name": "Gurpreet Singh", "email": "gurpreet@logciel.io", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/gurpreet-singh-7773553.jpg" },
        { "name": "Gurunatha Dogi", "email": "gurumatrix2004@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/gurunatha-dogi-7938522.jpg" },
        { "name": "Hake Sampatrao", "email": "sampatrao.baluhake@thalesgroup.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/hake-sampatrao-7746202.jpg" },
        { "name": "Hardik Arvindbhai Patel", "email": "hardikpatel043@yahoo.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/hardik-arvindbhai-patel-7960790.jpg" },
        { "name": "Harish Kumar Verma", "email": "harishverma555@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/harish-kumar-verma-7977097.jpg" },
        { "name": "Harpreet Singh Virdi", "email": "HarpreetSingh.Virdi@aristocrat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/harpreet-singh-virdi-7744542.jpg" },
        { "name": "Harsh Chhabra", "email": "chhabraharsh37@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/harsh-chhabra-7821425.jpg" },
        { "name": "Harsh Kumar", "email": "hkv1295@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/harsh-kumar-7946055.jpg" },
        { "name": "Harsh Raghuwanshi", "email": "harsharaghuwanshi094@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/harsh-raghuwanshi-7944524.jpg" },
        { "name": "Harshal Shirke", "email": "harshal.shirke@iauro.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/harshal-shirke-7979862.jpg" },
        { "name": "Harshit Badaya", "email": "harshitbadaya95@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/harshit-badaya-7681268.jpg" },
        { "name": "Harshit Sharma", "email": "harshit.sharma@thecompetenza.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/harshit-sharma-7769552.jpg" },
        { "name": "Harshita Verma", "email": "harshitav111@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/harshita-verma-7971788.jpg" },
        { "name": "Harvijay Singh", "email": "Harvijay.Singh@aristocrat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/harvijay-singh-7745544.jpg" },
        { "name": "Hemal Trivedi", "email": "hemal.trivedi@aisoftwarellc.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/hemal-trivedi-7783107.jpg" },
        { "name": "Himanshi Varshney", "email": "himanshi@telecrm.in", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/himanshi-varshney-7844325.jpg" },
        { "name": "Himanshu Goel", "email": "himanshu.goel.mca@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/himanshu-goel-7556190.jpg" },
        { "name": "Himanshu Kashyap", "email": "himanshu.kashyap@vtnetzwelt.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/himanshu-kashyap-8034438.jpg" },
        { "name": "Himanshu Sharma", "email": "himanshu.sharma@taazaa.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/himanshu-sharma-7775332.jpg" },
        { "name": "Hozefa Mangalorewala", "email": "hozefam@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/hozefa-mangalorewala-7613759.jpg" },
        { "name": "Insha Ramin", "email": "insharamin34@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/insha-ramin-7971406.jpg" },
        { "name": "Ishu Singhal", "email": "ishusinghal.official@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/ishu-singhal-7946418.jpg" },
        { "name": "Jagruti Jadhav", "email": "jagruti.jadhav@d2kindia.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/jagruti-jadhav-7745492.jpg" },
        { "name": "Jaideep Vidwani", "email": "jaideep@imriel.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/jaideep-vidwani-7926385.jpg" },
        { "name": "Janvhi Nagpal", "email": "janvhi.nagpal@sagunaconsulting.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/janvhi-nagpal-8008168.jpg" },
        { "name": "Jashanpreet Singh", "email": "jashanpreet.s@qservicesit.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/jashanpreet-singh-7882595.jpg" },
        { "name": "Jason Louis Baptista", "email": "jbaptista55.jb@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/jason-louis-baptista-7542383.jpg" },
        { "name": "Jaspal Singh", "email": "jaspalsingh183@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/jaspal-singh-7536154.jpg" },
        { "name": "Jaswinder Singh", "email": "geekyjaswinder@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/jaswinder-singh-7785430.jpg" },
        { "name": "Jatin Phulera", "email": "Jatin.Phulera@aristocrat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/jatin-phulera-7745624.jpg" },
        { "name": "Jay Mehta", "email": "jay@seaflux.tech", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/jay-mehta-7627634.jpg" },
        { "name": "Jay Sinha", "email": "jay.sinha@cat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/jay-sinha-7967869.jpg" },
        { "name": "Jibin Varghese John", "email": "jibin_1@hotmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/jibin-varghese-john-7957996.jpg" },
        { "name": "Jitendra Bhardwaj", "email": "bigtrader19@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/jitendra-bhardwaj-7963984.jpg" },
        { "name": "Jitendra Kumawat", "email": "jitendra.kumawat@thalesgroup.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/jitendra-kumawat-7746197.jpg" },
        { "name": "Jolly Paramjit", "email": "paramjit.jolly@thalesgroup.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/jolly-paramjit-7746193.jpg" },
        { "name": "Junaid Gehlot", "email": "junaid.gehlot@locobuzz.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/junaid-gehlot-8036243.jpg" },
        { "name": "Jyoti", "email": "jyoti@logiciel.io", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/jyoti-7773726.jpg" },
        { "name": "Kalpesh Bharambe", "email": "kalpesh.bharambe@nice.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/kalpesh-bharambe-7973543.jpg" },
        { "name": "Kamal Bhandari", "email": "kamal.bhandari.webdev@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/kamal-bhandari-7885772.jpg" },
        { "name": "Kapil Bhalala", "email": "kapilbhalala@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/kapil-bhalala-7532403.jpg" },
        { "name": "Karan Bir", "email": "karan@supremetechnologiesindia.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/karan-bir-7741090.jpg" },
        { "name": "Karan Kumar", "email": "karan.kumar@vtnetzwelt.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/karan-kumar-8034436.jpg" },
        { "name": "Karthikeyan", "email": "karthik3030@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/karthikeyan-7688559.jpg" },
        { "name": "Karthikeyan Krishnamurthy", "email": "krishnamurthy_karthikeyan@cat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/karthikeyan-krishnamurthy-7959778.jpg" },
        { "name": "Kartikey Rawat", "email": "rawatkari554@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/kartikey-rawat-7555143.jpg" },
        { "name": "Karuna Khatri", "email": "kkhatri@sharpquest.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/karuna-khatri-7880126.jpg" },
        { "name": "Kawaldeep Singh", "email": "kawaldeepsingh93@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/kawaldeep-singh-7790243.jpg" },
        { "name": "Ketan Chandrashekhar Valsangkar", "email": "ketan.valsangkar@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/ketan-chandrashekhar-valsangkar-7973694.jpg" },
        { "name": "Keyur Narkhi", "email": "knarkhi@matchbookservices.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/keyur-narkhi-7964259.jpg" },
        { "name": "Khadak H.Bist", "email": "questpond@questpond.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/khadak-h.bist-8035363.jpg" },
        { "name": "Kirankumar Sripati", "email": "krnsripati@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/kirankumar-sripati-7979958.jpg" },
        { "name": "Kirti Mittal", "email": "kirti.mittal@blackrock.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/kirti-mittal-7973727.jpg" },
        { "name": "Kshama Porwal", "email": "Kshama.Porwal@aristocrat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/kshama-porwal-7745580.jpg" },
        { "name": "Kuldeep Kumar", "email": "kumarkuldeepit@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/kuldeep-kumar-7767548.jpg" },
        { "name": "Kuldeep Sharma", "email": "Kuldeep.Sharma@aristocrat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/kuldeep-sharma-7744709.jpg" },
        { "name": "Kumar Arpit", "email": "arpit0472@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/kumar-arpit-7624276.jpg" },
        { "name": "Kundan Jha", "email": "kundan.niitd5@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/kundan-jha-7980275.jpg" },
        { "name": "Kushagra Kesav", "email": "kushagra198@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/kushagra-kesav-8004936.jpg" },
        { "name": "Lakshita Malhotra", "email": "lakshitamalhotra25@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/lakshita-malhotra-7781358.jpg" },
        { "name": "Lakshman S", "email": "lakshmansha1992@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/lakshman-s-7774643.jpg" },
        { "name": "Lalit Upreti", "email": "lalitupreti12@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/lalit-upreti-7963985.jpg" },
        { "name": "Linda Shiny", "email": "lindashiny@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/linda-shiny-7865776.jpg" },
        { "name": "Lokesh Kumar", "email": "lokesh.bansal@celebaltech.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/lokesh-kumar-8040578.jpg" },
        { "name": "Love Varshney", "email": "love@salesowl.co", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/love-varshney-7844326.jpg" },
        { "name": "Lovekesh Kumar", "email": "lovekesh.80@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/lovekesh-kumar-7774461.jpg" },
        { "name": "Maaz", "email": "maaz2dt@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/maaz-7661768.jpg" },
        { "name": "Madhav Bhagat", "email": "madhav@spotdraft.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/madhav-bhagat-7973210.jpg" },
        { "name": "Magnum Gupta", "email": "magnumgupta@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/magnum-gupta-8011471.jpg" },
        { "name": "Maha Lakshmi", "email": "mahalakshmis@syncfusion.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/maha-lakshmi-7909337.jpg" },
        { "name": "Mahalingam Raman", "email": "raman_mahlingam@cat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/mahalingam-raman-7967171.jpg" },
        { "name": "Mahaveer", "email": "mveer.jaipur@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/mahaveer-7792539.jpg" },
        { "name": "Mahesh Mandhare", "email": "smartmind25@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/mahesh-mandhare-7553883.jpg" },
        { "name": "Mahesh Shankar Bhandigare", "email": "msbhandigare@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/mahesh-shankar-bhandigare-7866096.jpg" },
        { "name": "Maithiliy K", "email": "maithiliyk@syncfusion.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/maithiliy-k-7909341.jpg" },
        { "name": "Mamta Rani", "email": "mamtarani039@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/mamta-rani-7684380.jpg" },
        { "name": "Manas Kumar", "email": "Manas.Kumar@aristocrat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/manas-kumar-7745775.jpg" },
        { "name": "Manav Goel", "email": "manav@geekyants.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/manav-goel-7931581.jpg" },
        { "name": "Manish Sharma", "email": "ermanisharma7@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/manish-sharma-8000674.jpg" },
        { "name": "Manoj Dubey", "email": "Manoj.Dubey@aristocrat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/manoj-dubey-7745806.jpg" },
        { "name": "Manoj Tyagi", "email": "tyagimanoj12@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/manoj-tyagi-7658085.jpg" },
        { "name": "Manpreet Singh", "email": "manpreet@bitfumes.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/manpreet-singh-7967319.jpg" },
        { "name": "Mansi Gupta", "email": "Mansi.Gupta@aristocrat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/mansi-gupta-7744981.jpg" },
        { "name": "Manvi Singhwal", "email": "manvisinghwal123@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/manvi-singhwal-7860703.jpg" },
        { "name": "Mayank Jain", "email": "mayankjain1394@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/mayank-jain-7712981.jpg" },
        { "name": "Mayur Pabari", "email": "mayur.pabari@smartsensesolutions.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/mayur-pabari-8036044.jpg" },
        { "name": "Mayur Patil", "email": "mayur.patil@aurelia.tech", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/mayur-patil-7553214.jpg" },
        { "name": "Meera Maheshkumar Purohit", "email": "meera.p110@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/meera-maheshkumar-purohit-7778302.jpg" },
        { "name": "Menka Chaugule", "email": "questpond@questpond.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/menka-chaugule-8035363.jpg" },
        { "name": "Mitesh Rathod", "email": "rathodmitesh42@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/mitesh-rathod-7553984.jpg" },
        { "name": "Mitul Nikunjkumar Gandhi", "email": "MGandhi3@slb.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/mitul-nikunjkumar-gandhi-7960789.jpg" },
        { "name": "Mohammad Khalid", "email": "khalid.bib@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/mohammad-khalid-7532624.jpg" },
        { "name": "Mohit Dasila", "email": "mohit@smartjoules.in", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/mohit-dasila-7974625.jpg" },
        { "name": "Mohit Saini", "email": "mohit.saini@qservicesit.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/mohit-saini-7882594.jpg" },
        { "name": "Mohit Saxena", "email": "Mohit.Saxena@aristocrat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/mohit-saxena-7744589.jpg" },
        { "name": "Mohsin Abbas Kalbe Hasan Shaikh", "email": "shaikh.mohsin@d2kindia.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/mohsin-abbas-kalbe-hasan-shaikh-7745494.jpg" },
        { "name": "Muhamed Shajeer", "email": "alshamilshj@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/muhamed-shajeer-7547500.jpg" },
        { "name": "Mukund Sonaiya", "email": "mukund.sonaiya@smartsensesolutions.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/mukund-sonaiya-7769098.jpg" },
        { "name": "Munish Sawhney", "email": "findmunish@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/munish-sawhney-7768292.jpg" },
        { "name": "Naga Sudhir Immadisetty", "email": "i.naga.sudhir@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/naga-sudhir-immadisetty-7879425.jpg" },
        { "name": "Nagendra Prajwal M", "email": "n.prajwal@f5.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/nagendra-prajwal-m-8019130.jpg" },
        { "name": "Nagesh Bulbule", "email": "questpond@questpond.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/nagesh-bulbule-8035363.jpg" },
        { "name": "Naufil Shaikh", "email": "snaufil09@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/naufil-shaikh-7783472.jpg" },
        { "name": "Navneet Kumar Sharma", "email": "sharma.navneet1988@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/navneet-kumar-sharma-7782921.jpg" },
        { "name": "Neeraj Sharma", "email": "neerajpl.odetocloud@dutechnosys.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/neeraj-sharma-8034285.jpg" },
        { "name": "Neeraj Sinha", "email": "neerajs@geekyants.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/neeraj-sinha-7938353.jpg" },
        { "name": "Nihal Kazi", "email": "nihal.kazi@pentaknot.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/nihal-kazi-7773532.jpg" },
        { "name": "Niharika Arora", "email": "nik.arora8059@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/niharika-arora-7861767.jpg" },
        { "name": "Nikunj V. Pandit", "email": "nikunj_0202@yahoo.co.in", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/nikunj-v.-pandit-7905185.jpg" },
        { "name": "Niloshima Srivastava", "email": "niloshima.srivastav@hotmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/niloshima-srivastava-7788196.jpg" },
        { "name": "Niral Munjariya", "email": "niralmunjariya@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/niral-munjariya-7553985.jpg" },
        { "name": "Niranjan Swain", "email": "niranjan.swain@thalesgroup.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/niranjan-swain-7746198.jpg" },
        { "name": "Nishant Gupta", "email": "nishangu@google.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/nishant-gupta-7970312.jpg" },
        { "name": "Nishant Kumar Agrawal", "email": "nishant@thecompetenza.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/nishant-kumar-agrawal-7769469.jpg" },
        { "name": "Nishant Shishodia", "email": "contact@radansimpextech.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/nishant-shishodia-7986418.jpg" },
        { "name": "Nitansh Bareja", "email": "nitansh.bareja@thalesgroup.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/nitansh-bareja-7746199.jpg" },
        { "name": "Nithin Gomez", "email": "nithin.gomez@cat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/nithin-gomez-7959777.jpg" },
        { "name": "Nitin Krishan", "email": "nitinkrish@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/nitin-krishan-7712227.jpg" },
        { "name": "Nitin Pandit", "email": "nitinpandit.00@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/nitin-pandit-7535826.jpg" },
        { "name": "Nitin Varshney", "email": "Nitin.Varshney@aristocrat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/nitin-varshney-7744511.jpg" },
        { "name": "Nitish Kumar", "email": "nitishk72@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/nitish-kumar-7982665.jpg" },
        { "name": "Nitish Thakrar", "email": "nitish.thakrar@seaflux.tech", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/nitish-thakrar-7627635.jpg" },
        { "name": "Noor Peersab", "email": "noor.peersab@neptune-ubi.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/noor-peersab-7815905.jpg" },
        { "name": "Nuthanchandra N", "email": "n.n@f5.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/nuthanchandra-n-8019101.jpg" },
        { "name": "Omprakash Amarwal", "email": "omprakash.amarwal@d2kindia.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/omprakash-amarwal-7745489.jpg" },
        { "name": "Omprakash Biswal", "email": "biswalom22@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/omprakash-biswal-7545877.jpg" },
        { "name": "P Sekhar Babu", "email": "sekharbabu101@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/p-sekhar-babu-7780607.jpg" },
        { "name": "Pankaj Gupta", "email": "guptagpankaj@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/pankaj-gupta-7545795.jpg" },
        { "name": "Pankhuri Kansal", "email": "Pankhuri.Kansal@aristocrat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/pankhuri-kansal-7744714.jpg" },
        { "name": "Param Agarwal", "email": "191b178@juetguna.in", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/param-agarwal-7707625.jpg" },
        { "name": "Pardeep Kumar", "email": "mkumarpardeep@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/pardeep-kumar-7534000.jpg" },
        { "name": "Pardeep Rathee", "email": "Pardeep.Rathee@aristocrat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/pardeep-rathee-7745097.jpg" },
        { "name": "Parita Todai", "email": "parita.7todai@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/parita-todai-7958644.jpg" },
        { "name": "Paritoshik Paul", "email": "paritoshik.paul@srijan.net", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/paritoshik-paul-7939414.jpg" },
        { "name": "Parkash Singh", "email": "parkash2885@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/parkash-singh-7977168.jpg" },
        { "name": "Parth Shah", "email": "parth.shah@imriel.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/parth-shah-7926383.jpg" },
        { "name": "Pawan Arora", "email": "pawan@logiciel.io", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/pawan-arora-7773607.jpg" },
        { "name": "Pawan Kumar", "email": "pawan221b@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/pawan-kumar-7967628.jpg" },
        { "name": "Phalgun Vaddepalli", "email": "phalgun251@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/phalgun-vaddepalli-7688241.jpg" },
        { "name": "Piyush Jain", "email": "jainpiyush005@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/piyush-jain-7776475.jpg" },
        { "name": "Piyush Sharma", "email": "sharmapiyush8888@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/piyush-sharma-7663683.jpg" },
        { "name": "Piyushkumar C. Kacha", "email": "pkacha@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/piyushkumar-c.-kacha-7677789.jpg" },
        { "name": "Pooja Parkar", "email": "parkarpankaj3@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/pooja-parkar-8033815.jpg" },
        { "name": "Pooja Tak", "email": "poojatak04@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/pooja-tak-7699904.jpg" },
        { "name": "Prabpreet S Chaman", "email": "pracha@7n.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/prabpreet-s-chaman-7938561.jpg" },
        { "name": "Pradeep Kumar", "email": "Pradeep.Kumar@aristocrat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/pradeep-kumar-7745784.jpg" },
        { "name": "Prameela Mula", "email": "prameela.mula@hexagon.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/prameela-mula-7832776.jpg" },
        { "name": "Pranav Barot", "email": "pranav.barot@qdevtechnolab.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/pranav-barot-7844070.jpg" },
        { "name": "Prashant Khadka", "email": "questpond@questpond.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/prashant-khadka-8035363.jpg" },
        { "name": "Prateek Mishra", "email": "prateek.m046@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/prateek-mishra-7673014.jpg" },
        { "name": "Prathamesh Ashra", "email": "prathameshedu@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/prathamesh-ashra-7773534.jpg" },
        { "name": "Praveen Kumar", "email": "praveenkumar@smartjoules.in", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/praveen-kumar-7977352.jpg" },
        { "name": "Praveen Singh", "email": "psraj86@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/praveen-singh-7555031.jpg" },
        { "name": "Praveen Yadav", "email": "Praveen.Yadav@aristocrat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/praveen-yadav-7745615.jpg" },
        { "name": "Preeti Arora", "email": "Preeti.Arora@aristocrat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/preeti-arora-7744999.jpg" },
        { "name": "Preksha Sachdeva", "email": "preksha.sachdeva@iauro.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/preksha-sachdeva-7979863.jpg" },
        { "name": "Priti Patil", "email": "questpond@questpond.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/priti-patil-8035363.jpg" },
        { "name": "Priyank Agarwal", "email": "pagarwal11@slb.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/priyank-agarwal-7960791.jpg" },
        { "name": "Promila", "email": "promila@logiciel.io", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/promila-7773700.jpg" },
        { "name": "Puja Kumari", "email": "beingpuja1996@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/puja-kumari-8005033.jpg" },
        { "name": "Purinder Chawla", "email": "Purinder.Chawla@aristocrat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/purinder-chawla-7744501.jpg" },
        { "name": "Pushpinder Singh", "email": "pushpinder1997.ps@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/pushpinder-singh-7971059.jpg" },
        { "name": "Rahul Grover", "email": "rahul.grover@pentaknot.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/rahul-grover-7773531.jpg" },
        { "name": "Rahul Mohan Gupta", "email": "rahulmohan82@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/rahul-mohan-gupta-7838634.jpg" },
        { "name": "Rahul Sharma", "email": "rahul.sharma@thecompetenza.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/rahul-sharma-7775040.jpg" },
        { "name": "Rajan Kumar", "email": "rajan-kumar@outlook.in", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/rajan-kumar-7545109.jpg" },
        { "name": "Rajan Sharma", "email": "sharma.rajan3097@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/rajan-sharma-7663684.jpg" },
        { "name": "Rajat Sharma", "email": "march10rajat@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/rajat-sharma-7768840.jpg" },
        { "name": "Rajeev Ranjan", "email": "rajeev.ranjan86@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/rajeev-ranjan-7646579.jpg" },
        { "name": "Rajesh Yalamarthy", "email": "rajesh.yalamarthi@hexagon.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/rajesh-yalamarthy-7832775.jpg" },
        { "name": "Rajeswar Indumukhi", "email": "i.rajeswar24@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/rajeswar-indumukhi-7646742.jpg" },
        { "name": "Rajkamal Ramalingam", "email": "ramalingam_rajkamal@cat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/rajkamal-ramalingam-7966987.jpg" },
        { "name": "Rajmani Prasad", "email": "rprasad@okkular.io", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/rajmani-prasad-7972962.jpg" },
        { "name": "Rakesh Chaudhari", "email": "rakesh.chaudhari@centiro.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/rakesh-chaudhari-7775396.jpg" },
        { "name": "Rakesh Pandey", "email": "rakeesh.k01@rediffmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/rakesh-pandey-8033363.jpg" },
        { "name": "Ramdasu Ravipudi", "email": "rravipudi@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/ramdasu-ravipudi-7775879.jpg" },
        { "name": "Ramesh Narayan Javale", "email": "ram4u2006@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/ramesh-narayan-javale-7905183.jpg" },
        { "name": "Ranjan Kumar", "email": "ranjan@kormoan.in", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/ranjan-kumar-7552663.jpg" },
        { "name": "Rasika Sutar", "email": "rasika.sutar@d2kindia.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/rasika-sutar-7745493.jpg" },
        { "name": "Rasmiranjan Nayak", "email": "rasmiranjan.nayak@thalesgroup.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/rasmiranjan-nayak-7746200.jpg" },
        { "name": "Ravi Heer", "email": "raviheer22@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/ravi-heer-7544387.jpg" },
        { "name": "Ravi Prajapati", "email": "raviprajapati141297@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/ravi-prajapati-7905456.jpg" },
        { "name": "Ravi Prakash Rai", "email": "RaviPrakash.Rai@aristocrat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/ravi-prakash-rai-7744956.jpg" },
        { "name": "Ravinder Singh", "email": "kumarravinder0786@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/ravinder-singh-7545083.jpg" },
        { "name": "Richa", "email": "Richakurra164@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/richa-7748312.jpg" },
        { "name": "Rishabh", "email": "Rishabh@aristocrat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/rishabh-7745537.jpg" },
        { "name": "Rishabh Awasthi", "email": "awasrishabh@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/rishabh-awasthi-7535778.jpg" },
        { "name": "Rishabh Bakshi", "email": "bakshirishab90@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/rishabh-bakshi-7775377.jpg" },
        { "name": "Rishabh Nasa", "email": "rishabh26.rn@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/rishabh-nasa-7957542.jpg" },
        { "name": "Ritesh Kumar", "email": "Ritesh.Kumar@aristocrat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/ritesh-kumar-7745558.jpg" },
        { "name": "Ritesh Singh", "email": "Ritesh.Singh@aristocrat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/ritesh-singh-7744604.jpg" },
        { "name": "Rohan Thakur", "email": "rohan.thaakur@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/rohan-thakur-7543273.jpg" },
        { "name": "Rohit Chopra", "email": "crohit92@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/rohit-chopra-7777830.jpg" },
        { "name": "Rohit Dabra", "email": "rohit.dabra@qservicesit.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/rohit-dabra-7882593.jpg" },
        { "name": "Rohit Kumar Pandit", "email": "rohitk@taazaa.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/rohit-kumar-pandit-7775331.jpg" },
        { "name": "Rohit Yadav", "email": "rohit1801.yadav@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/rohit-yadav-7952102.jpg" },
        { "name": "Ronak Thacker", "email": "ronak.thacker@smartsensesolutions.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/ronak-thacker-7769097.jpg" },
        { "name": "Roshan Gavandi", "email": "roshan.gavandi@nginxus.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/roshan-gavandi-7545842.jpg" },
        { "name": "Ruchir Gupta", "email": "ruchir98@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/ruchir-gupta-7957307.jpg" },
        { "name": "Rupesh Suhdir Kadam", "email": "kadam.rupesh28297@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/rupesh-suhdir-kadam-7809880.jpg" },
        { "name": "Sachin Bonde", "email": "sachin.bonde@d2kindia.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/sachin-bonde-7745490.jpg" },
        { "name": "Sachin Khare", "email": "s.khare@f5.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/sachin-khare-8019161.jpg" },
        { "name": "Sachin Ojha", "email": "sachin.ojha9993@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/sachin-ojha-7532733.jpg" },
        { "name": "Sachiv Mehta", "email": "sachiv.mehta.9@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/sachiv-mehta-7545222.jpg" },
        { "name": "Sagar Panwar", "email": "Sagar.Panwar@aristocrat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/sagar-panwar-7744581.jpg" },
        { "name": "Saheb Singh Tuteja", "email": "saheb.singh@seaflux.tech", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/saheb-singh-tuteja-7627637.jpg" },
        { "name": "Sahithya Mulapalli", "email": "sahithya.mulapalli@enverus.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/sahithya-mulapalli-7955893.jpg" },
        { "name": "Sai Kiran Marripati", "email": "saikiranmarripati@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/sai-kiran-marripati-7881476.jpg" },
        { "name": "Sajjan Rampal", "email": "rampal.sajjan@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/sajjan-rampal-7978051.jpg" },
        { "name": "Saksham Taneja", "email": "sakshamtaneja7861@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/saksham-taneja-7904079.jpg" },
        { "name": "Sakshi Gondane", "email": "sakshi.gondane@centiro.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/sakshi-gondane-7775397.jpg" },
        { "name": "Saleem Malik Raja Kader Meera", "email": "Raja_Saleem_K@cat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/saleem-malik-raja-kader-meera-7967868.jpg" },
        { "name": "Sanchit Khurana", "email": "sanchitkhuranask@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/sanchit-khurana-8010319.jpg" },
        { "name": "Sandeep G. Bansod", "email": "sndpbansod5@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/sandeep-g.-bansod-7783018.jpg" },
        { "name": "Sandip Barot", "email": "sbarot@matchbookai.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/sandip-barot-7964227.jpg" },
        { "name": "Sangeeta Kumawat", "email": "sangeeta.kumawat@celebaltech.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/sangeeta-kumawat-8040579.jpg" },
        { "name": "Sanjay Bhargava", "email": "sanjay.bhargava89@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/sanjay-bhargava-7877269.jpg" },
        { "name": "Sanjay Kumar", "email": "webmasters964@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/sanjay-kumar-7771522.jpg" },
        { "name": "Sanjit Raj Shakya", "email": "questpond@questpond.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/sanjit-raj-shakya-8035363.jpg" },
        { "name": "Sanket Mishra", "email": "sanket@spotdraft.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/sanket-mishra-7955826.jpg" },
        { "name": "Sapan Sheth", "email": "sapan.sheth@neptune-ubi.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/sapan-sheth-7815904.jpg" },
        { "name": "Saquib Ajaz", "email": "saquib.ajaz@srijan.net", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/saquib-ajaz-7952322.jpg" },
        { "name": "Sarthak Negi", "email": "sarthakn18@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/sarthak-negi-7806124.jpg" },
        { "name": "Sarthak Shrivastava", "email": "bitfumes@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/sarthak-shrivastava-7668498.jpg" },
        { "name": "Sarvesh Shinde", "email": "sarvesh.shinde@locobuzz.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/sarvesh-shinde-8036245.jpg" },
        { "name": "Sathish Kesavaperumal", "email": "kesavaperumal_sathish@cat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/sathish-kesavaperumal-7966996.jpg" },
        { "name": "Saumya Vishwari", "email": "somyavishwari@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/saumya-vishwari-7962526.jpg" },
        { "name": "Saurabh Singh Tomar", "email": "SaurabhSingh.Tomar@aristocrat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/saurabh-singh-tomar-7745112.jpg" },
        { "name": "Saurabh Srivastava", "email": "saurabhsri@geekyants.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/saurabh-srivastava-7931582.jpg" },
        { "name": "Saurav Dubey", "email": "dubeysaurav153@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/saurav-dubey-7758989.jpg" },
        { "name": "Sayash Chaudhary", "email": "sayashchaudhary@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/sayash-chaudhary-7771888.jpg" },
        { "name": "Shahwaz Ahmed Khan", "email": "shahwazak@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/shahwaz-ahmed-khan-7938718.jpg" },
        { "name": "Shaifali Kalia", "email": "shaifali@logiciel.io", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/shaifali-kalia-7773606.jpg" },
        { "name": "Shailendra Kumar P", "email": "s.pallikonda@f5.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/shailendra-kumar-p-8000620.jpg" },
        { "name": "Shaiwaz Ansari", "email": "shaiwaz.ansari@locobuzz.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/shaiwaz-ansari-8036244.jpg" },
        { "name": "Shakti Singh Dulawat", "email": "shakti@odetocloud.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/shakti-singh-dulawat-8034286.jpg" },
        { "name": "Shikhar Agarwal", "email": "shikharagarwal2807@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/shikhar-agarwal-7771889.jpg" },
        { "name": "Shiv Shankar Kumar", "email": "sh.kumar@f5.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/shiv-shankar-kumar-8019075.jpg" },
        { "name": "Shiva Manduvakuriti", "email": "Shiva.Manduvakuriti@hexagon.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/shiva-manduvakuriti-7832777.jpg" },
        { "name": "Shivam Mishra", "email": "shivam.mishra@celebaltech.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/shivam-mishra-8040580.jpg" },
        { "name": "Shivay Lamba", "email": "shivaylamba@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/shivay-lamba-7808022.jpg" },
        { "name": "Shivendra Pratap Singh", "email": "shivendrapratapsingh660@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/shivendra-pratap-singh-7837539.jpg" },
        { "name": "Shivika Singla", "email": "shivika.singla@vtnetzwelt.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/shivika-singla-8034437.jpg" },
        { "name": "Shivling Giramalayya Swami", "email": "shivling.swami29@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/shivling-giramalayya-swami-7866095.jpg" },
        { "name": "Shlok Chavan", "email": "shlok@pentaknot.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/shlok-chavan-7773530.jpg" },
        { "name": "Shrey", "email": "shrey8340@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/shrey-7944420.jpg" },
        { "name": "Shreya Prasad", "email": "shreyapd06@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/shreya-prasad-8041693.jpg" },
        { "name": "Shristi Shukla", "email": "shristi0901@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/shristi-shukla-7987041.jpg" },
        { "name": "Shubham Kumar", "email": "namithubot@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/shubham-kumar-7769924.jpg" },
        { "name": "Shubham Kumar", "email": "sk101294@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/shubham-kumar-7951678.jpg" },
        { "name": "Shubham Seth", "email": "shubhamseth29007@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/shubham-seth-7764614.jpg" },
        { "name": "Shubhamsatyam Verma", "email": "shubhamsv@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/shubhamsatyam-verma-7545671.jpg" },
        { "name": "Shweta Patil", "email": "shweta.patil@centiro.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/shweta-patil-7775399.jpg" },
        { "name": "Simran Bist", "email": "questpond@questpond.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/simran-bist-8035363.jpg" },
        { "name": "Simran Chaudhary", "email": "simrandhinwa@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/simran-chaudhary-7720126.jpg" },
        { "name": "Sivakumar R", "email": "sivakumarr@syncfusion.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/sivakumar-r-7909338.jpg" },
        { "name": "Sneha Patil", "email": "snpatil@deloitte.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/sneha-patil-7971779.jpg" },
        { "name": "Sneha Susan Shibu", "email": "shibu@7n.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/sneha-susan-shibu-7938575.jpg" },
        { "name": "Sohail Pathan", "email": "iamspathan@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/sohail-pathan-7971205.jpg" },
        { "name": "Soham Acharya", "email": "hemal.trivedi@aisoftwarellc.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/soham-acharya-7783107.jpg" },
        { "name": "Somnath Ravindra Shintre", "email": "somnathshintre77@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/somnath-ravindra-shintre-7866098.jpg" },
        { "name": "Sonam Raj", "email": "sonam@qservicesit.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/sonam-raj-7882596.jpg" },
        { "name": "Sooraj Singh", "email": "sooraj12002@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/sooraj-singh-7554558.jpg" },
        { "name": "Soumen Mukherjee", "email": "soumen.mukherjee@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/soumen-mukherjee-7532904.jpg" },
        { "name": "Sri Harsha Koppella", "email": "s.kopella@f5.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/sri-harsha-koppella-8019049.jpg" },
        { "name": "Stephen Simon", "email": "a.stephensimon@outlook.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/stephen-simon-7533072.jpg" },
        { "name": "Subodh Modgil", "email": "Subodh.Modgil@aristocrat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/subodh-modgil-7745040.jpg" },
        { "name": "Suchita Goel", "email": "Suchita.Goel@aristocrat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/suchita-goel-7744531.jpg" },
        { "name": "Sudeep Gujju", "email": "sudeepgujju@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/sudeep-gujju-7881477.jpg" },
        { "name": "Sudhanshu Ram Tripathi", "email": "tripathisudhanshuram@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/sudhanshu-ram-tripathi-7961678.jpg" },
        { "name": "Sudhanshumamgain", "email": "mamgainsudhanshu@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/sudhanshumamgain-7663761.jpg" },
        { "name": "Sudheshwer Rai", "email": "sudheshwer.tech@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/sudheshwer-rai-7536762.jpg" },
        { "name": "Sukhdev Sharma", "email": "Sukhdev.Sharma@aristocrat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/sukhdev-sharma-7745699.jpg" },
        { "name": "Sumesh Joshi", "email": "questpond@questpond.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/sumesh-joshi-8035363.jpg" },
        { "name": "Sumit Kumar", "email": "sumitsri9@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/sumit-kumar-7542851.jpg" },
        { "name": "Sumit Kumar", "email": "sum.kumar@f5.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/sumit-kumar-7999301.jpg" },
        { "name": "Sunabha Sinha", "email": "mailsunabha@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/sunabha-sinha-7776913.jpg" },
        { "name": "Sunny Fernandes", "email": "sunny.fernandes@d2kindia.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/sunny-fernandes-7745491.jpg" },
        { "name": "Supriya Sanjay Kumawat", "email": "developersupriya18@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/supriya-sanjay-kumawat-7815999.jpg" },
        { "name": "Surabhi Seth", "email": "sseth5@slb.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/surabhi-seth-7960786.jpg" },
        { "name": "Suraj Ramakant Bhojane", "email": "bhojanesuraj231@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/suraj-ramakant-bhojane-7618564.jpg" },
        { "name": "Suraj Singh", "email": "Suraj.Singh@aristocrat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/suraj-singh-7745028.jpg" },
        { "name": "Suraj Soni", "email": "Suraj.Soni@aristocrat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/suraj-soni-7745798.jpg" },
        { "name": "Suraj Suresh Bande", "email": "surajbande007@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/suraj-suresh-bande-7536741.jpg" },
        { "name": "Surojit Bhattacharjee", "email": "surojit.bhattacharjee@taazaa.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/surojit-bhattacharjee-7775328.jpg" },
        { "name": "Surya Teja Hanumandla", "email": "s.hanumandla@f5.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/surya-teja-hanumandla-8019091.jpg" },
        { "name": "Suryakant Singh", "email": "Suryakant.Singh@aristocrat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/suryakant-singh-7744535.jpg" },
        { "name": "Susmita Mitra", "email": "susmitamitra.mca@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/susmita-mitra-7872512.jpg" },
        { "name": "Swastika Yadav", "email": "swastikayadav5358@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/swastika-yadav-7915343.jpg" },
        { "name": "Swati Badhwar", "email": "swati.badhwar@taazaa.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/swati-badhwar-7775330.jpg" },
        { "name": "Swati Chopra", "email": "swati.chopra@blackrock.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/swati-chopra-7952474.jpg" },
        { "name": "Swetank Rathi", "email": "swetankrathi@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/swetank-rathi-7971792.jpg" },
        { "name": "Tajinderpal Singh", "email": "tajinder@logiciel.io", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/tajinderpal-singh-7775360.jpg" },
        { "name": "Tapendra Kumar Sharma", "email": "tapendra.sharma4@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/tapendra-kumar-sharma-7769393.jpg" },
        { "name": "Tariq Aqeel", "email": "tariq.aqeel008@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/tariq-aqeel-7757173.jpg" },
        { "name": "Tashi Gautam", "email": "tashub3@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/tashi-gautam-7841088.jpg" },
        { "name": "Tejas Sathe", "email": "tejas.sathe@centiro.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/tejas-sathe-7775400.jpg" },
        { "name": "Tushar Joshi", "email": "tusharvjoshi@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/tushar-joshi-7534234.jpg" },
        { "name": "Tushar Sharma", "email": "tusharsharma314@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/tushar-sharma-7946419.jpg" },
        { "name": "Umesh Kumar", "email": "umesh1134@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/umesh-kumar-7532471.jpg" },
        { "name": "Urvesh Manilal Nagda", "email": "urvesh_nagda@yahoo.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/urvesh-manilal-nagda-7985997.jpg" },
        { "name": "Utkarsh Chakravarty", "email": "chakravartyutkarsh@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/utkarsh-chakravarty-7771887.jpg" },
        { "name": "Utkarsh Singh", "email": "utkarshsinghmca@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/utkarsh-singh-7539578.jpg" },
        { "name": "Valan Packianathan", "email": "p_valan@cat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/valan-packianathan-7959776.jpg" },
        { "name": "Vallambatla Nishanth Chandra", "email": "ncvallambatla@google.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/vallambatla-nishanth-chandra-7970941.jpg" },
        { "name": "Vandana Sharma", "email": "vandana.sharma@thalesgroup.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/vandana-sharma-7746201.jpg" },
        { "name": "Varun Gupta", "email": "thevarungupta5@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/varun-gupta-7992144.jpg" },
        { "name": "Varun S", "email": "varun1505@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/varun-s-7542553.jpg" },
        { "name": "Vidushi Dwivedi", "email": "vidushidwivedi51@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/vidushi-dwivedi-7716536.jpg" },
        { "name": "Vijay Dwivedi", "email": "vijaydwivedi125@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/vijay-dwivedi-7532903.jpg" },
        { "name": "Vijayagopan K Sadagopan", "email": "kanniapillai_sadagopan_vijayagopan@cat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/vijayagopan-k-sadagopan-7951049.jpg" },
        { "name": "Vikas Palan", "email": "vipa@7n.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/vikas-palan-7938588.jpg" },
        { "name": "Vikash Sharma", "email": "Vikash.Sharma@aristocrat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/vikash-sharma-7745570.jpg" },
        { "name": "Vinay Bhandari", "email": "vinay@nextgenapps.in", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/vinay-bhandari-7746529.jpg" },
        { "name": "Vinay Faye", "email": "vinay.faye@centiro.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/vinay-faye-7775398.jpg" },
        { "name": "Vinay Kamalakar Limaye", "email": "vinay.limaye@thecompetenza.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/vinay-kamalakar-limaye-7769271.jpg" },
        { "name": "Vinit Shashikant Zanje", "email": "vinitzanje@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/vinit-shashikant-zanje-7806123.jpg" },
        { "name": "Vipin Bhandari", "email": "vipin.doon.2@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/vipin-bhandari-7717995.jpg" },
        { "name": "Vishal Sharma", "email": "vishaltiwari9521@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/vishal-sharma-7769531.jpg" },
        { "name": "Vishesh Dahate", "email": "visda@7n.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/vishesh-dahate-7938583.jpg" },
        { "name": "Vishwam Gupta", "email": "Vishwam.Gupta@aristocrat.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/vishwam-gupta-7744705.jpg" },
        { "name": "Vishwaraj Sanjay Chavan", "email": "vishwarajchavan123@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/vishwaraj-sanjay-chavan-7866093.jpg" },
        { "name": "Vivek Kwatra", "email": "vivekkwatra@hotmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/vivek-kwatra-7701708.jpg" },
        { "name": "Vrajendra Singh Rana", "email": "vrana@7n.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/vrajendra-singh-rana-7938543.jpg" },
        { "name": "Vrijraj Singh", "email": "vrijraj2396@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/vrijraj-singh-7971134.jpg" },
        { "name": "Yajas Sardana", "email": "yajassardana@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/yajas-sardana-7999772.jpg" },
        { "name": "Yashika Aggarwal", "email": "aggarwal.yashika12@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/yashika-aggarwal-7717233.jpg" },
        { "name": "Yogasundaram", "email": "yogasundaram.asd30@gmail.com", "ecert-url": "https://ngind2022.blob.core.windows.net/ecerts/yogasundaram-7533981.jpg" }
    ]

    public getCertficate(email: string, name: string) {

        let data = this.allCertficates.findIndex(c => c.name == name && c.email == email);
        if(data == -1){
           return "Provided Email Does not Exist";
        }
        else {
            return this.allCertficates[data];
        }
        
    }
}
